/*
 * Party Role Management
 * This is Swagger UI environment generated for the TMF Party Role Management specification
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.tmf669.api;

import io.swagger.tmf669.model.EventSubscription;
import io.swagger.tmf669.model.EventSubscriptionInput;
import org.junit.Ignore;
import org.junit.Test;


/**
 * API tests for EventsSubscriptionApi
 */
@Ignore
public class EventsSubscriptionApiTest {

    private final io.swagger.tmf669.api.EventsSubscriptionApi api = new EventsSubscriptionApi();

    /**
     * Register a listener
     *
     * Sets the communication endpoint address the service instance must use to deliver information about its health state, execution state, failures and metrics.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void registerListenerTest() throws Exception {
        EventSubscriptionInput body = null;
        EventSubscription response = api.registerListener(body);

        // TODO: test validations
    }
    /**
     * Unregister a listener
     *
     * Resets the communication endpoint address the service instance must use to deliver information about its health state, execution state, failures and metrics.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void unregisterListenerTest() throws Exception {
        String id = null;
        api.unregisterListener(id);

        // TODO: test validations
    }
}
