/*
 * Party Role Management
 * This is Swagger UI environment generated for the TMF Party Role Management specification
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.tmf669.api;

import io.swagger.tmf669.model.PartyRole;
import io.swagger.tmf669.model.PartyRoleCreate;
import io.swagger.tmf669.model.PartyRoleUpdate;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;


/**
 * API tests for PartyRoleApi
 */
@Ignore
public class PartyRoleApiTest {

    private final io.swagger.tmf669.api.PartyRoleApi api = new PartyRoleApi();

    /**
     * Creates a PartyRole
     *
     * This operation creates a PartyRole entity.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createPartyRoleTest() throws Exception {
        PartyRoleCreate body = null;
        PartyRole response = api.createPartyRole(body);

        // TODO: test validations
    }
    /**
     * Deletes a PartyRole
     *
     * This operation deletes a PartyRole entity.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deletePartyRoleTest() throws Exception {
        String id = null;
        api.deletePartyRole(id);

        // TODO: test validations
    }
    /**
     * List or find PartyRole objects
     *
     * This operation list or find PartyRole entities
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listPartyRoleTest() throws Exception {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<PartyRole> response = api.listPartyRole(fields, offset, limit);

        // TODO: test validations
    }
    /**
     * Updates partially a PartyRole
     *
     * This operation updates partially a PartyRole entity.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void patchPartyRoleTest() throws Exception {
        PartyRoleUpdate body = null;
        String id = null;
        PartyRole response = api.patchPartyRole(body, id);

        // TODO: test validations
    }
    /**
     * Retrieves a PartyRole by ID
     *
     * This operation retrieves a PartyRole entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void retrievePartyRoleTest() throws Exception {
        String id = null;
        String fields = null;
        PartyRole response = api.retrievePartyRole(id, fields);

        // TODO: test validations
    }
}
